### ISSUE TITLE
How to save?

### ISSUE THREAD

**Issue by Researcher33** [ikolokotronis/CustomPasswordGenerator#1]
Hello, how can we collect each generated password in a file as a document.

**Comment by ikolokotronis** [comment]
Hello, there is no saving implemented in this app but I'd be happy to work on this feature. Let me know what you think

**Comment by Researcher33** [comment]
Let's save each generated password (eg: generated passwords.txt) file. How can we do this. ?

**Comment by ikolokotronis** [comment]
We can use FileSaver.js for that (https://github.com/eligrey/FileSaver.js/). Also, to make a list of generated passwords, we could store each generated password in a mutual array so that we will know which passwords will be saved. What do you think?

**Comment by ikolokotronis** [comment]
I actually added this function in my latest commit called "Password saving functionality". Check it out and let me know if you have any questions.

**Comment by Researcher33** [comment]
It's amazing. Thank you very much for your time and attention.

**Comment by ikolokotronis** [comment]
You're welcome
